kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-www
  labels:
    app: nginx
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi