apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: edge-clusters
  namespace: cattle-monitoring-system
  labels:
    cluster: edge-clusters
spec:
  endpoints:
    - interval: 1m
      honorLabels: true
      scrapeTimeout: 55s
      path: "/metrics"
      port: node-exporter
      metricRelabelings:
        - sourceLabels:
            - service
          targetLabel: cluster
    - interval: 1m
      honorLabels: true
      scrapeTimeout: 55s
      path: "/metrics"
      port: kube-state-metrics
      metricRelabelings:
        - sourceLabels:
            - service
          targetLabel: cluster
  namespaceSelector:
    matchNames:
      - cattle-monitoring-system
  selector:
    matchLabels:
      cluster: edge-clusters
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-one
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
spec:
  type: ExternalName
  externalName: 18.156.119.236
  clusterIP: ""
  ports:
    - port: 9100
      targetPort: 9100
      name: node-exporter
      protocol: TCP
    - port: 30080
      targetPort: 30080
      name: kube-state-metrics
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cluster-one
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
subsets:
  - addresses:
      - ip: 18.156.119.236
    ports:
      - port: 9100
        name: node-exporter
        protocol: TCP
      - port: 30080
        name: kube-state-metrics
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-two
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
spec:
  type: ExternalName
  externalName: 54.246.50.116
  clusterIP: ""
  ports:
    - port: 9100
      targetPort: 9100
      name: node-exporter
      protocol: TCP
    - port: 30080
      targetPort: 30080
      name: kube-state-metrics
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cluster-two
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
subsets:
  - addresses:
      - ip: 54.246.50.116
    ports:
      - port: 9100
        name: node-exporter
        protocol: TCP
      - port: 30080
        name: kube-state-metrics
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-three
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
spec:
  type: ExternalName
  externalName: 3.66.225.46
  clusterIP: ""
  ports:
    - port: 9100
      targetPort: 9100
      name: node-exporter
      protocol: TCP
    - port: 30080
      targetPort: 30080
      name: kube-state-metrics
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cluster-three
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
subsets:
  - addresses:
      - ip: 3.66.225.46
    ports:
      - port: 9100
        name: node-exporter
        protocol: TCP
      - port: 30080
        name: kube-state-metrics
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-four
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
spec:
  type: ExternalName
  externalName: 34.244.139.148
  clusterIP: ""
  ports:
    - port: 9100
      targetPort: 9100
      name: node-exporter
      protocol: TCP
    - port: 30080
      targetPort: 30080
      name: kube-state-metrics
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cluster-four
  labels:
    cluster: edge-clusters
  namespace: cattle-monitoring-system
subsets:
  - addresses:
      - ip: 34.244.139.148
    ports:
      - port: 9100
        name: node-exporter
        protocol: TCP
      - port: 30080
        name: kube-state-metrics
        protocol: TCP